### ISSUE TITLE
restart and shutdown menu gone

### ISSUE THREAD

**Issue by sv0o** [tobiasgraf/OctoPrint-Octo4a_battery#2]
I love this plugin.  I'm using my wife's old LG phone with a beat up USB micro port and I need to see if the battery is almost dead....

I do miss having the power button menu with restart and shutdown options.  Also, along the lines of saving the battery, I'd like to be able to "logout" again.  Do you have to be constantly logged in for the battery display to work?

Thanks.

**Comment by Gerigot** [comment]
I have the same problem I'm trying to find a solution I think that modifing custom_bindings to True for the navbar could be the way to go, but I'm really new in plugin development.

`def get_template_configs(self):
        return [
            dict(type="navbar", custom_bindings=True),
            dict(type="settings", custom_bindings=False)
        ]`

**Comment by sv0o** [comment]
I'm interested in what you discover but I stopped using the plugin when I found a way to run octo4a on an androidTV box.

**Comment by Gerigot** [comment]
I tried the version with my octo4a and with that change it works so I made a pull request (#3 )

**Comment by tobiasgraf** [comment]
should be resolved by #3

**Comment by sv0o** [comment]
tested and works.  This gives me a good way to keep a backup octoprint server on hand.
